apiVersion: v1
kind: Service
metadata:
  name: go-app-service      
spec:
  selector:                  
    app: goapp-git  
  ports:
  - name: 8080-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8081         